### ISSUE TITLE
Mac Support issue: Default Port

### ISSUE THREAD

**Issue by EliJArmstrong** [danqzq/unity-twitch-chat-interactions#12]
Hello,

I want to express my gratitude for this library; it has proven to be incredibly helpful.

I'd like to highlight a minor issue that users might encounter when utilizing this library on a Mac, or share a helpful tip.

By default, attempting to access http://localhost/ or http://127.0.0.1/ might result in an "access denied" error when using the Auth code on a Mac. The workaround is straightforward—simply append a port to the end of the URL:

![image](https://github.com/danqzq/unity-twitch-chat-interactions/assets/41320998/e756924f-a76f-483d-9439-983b066195ee)

However, when implementing this change, please remember to update the Redirect URL in the settings and within the Twitch API Dashboard:

![image](https://github.com/danqzq/unity-twitch-chat-interactions/assets/41320998/5d3b4105-6a14-4008-8b4f-f089cceae44c)
![image](https://github.com/danqzq/unity-twitch-chat-interactions/assets/41320998/1e2772ac-fdd3-45eb-ac73-435ba6b778cb)

This adjustment should resolve the issue and allow for smooth functionality on both Mac and other systems.

Thank you again,
Eli

**Comment by danqzq** [comment]
Hello Eli!

Thank you for testing it out on Mac! I will pull out a fix for this asap and roll out a new Unity package. I appreciate your contribution!

Kind regards,
Dan

**Comment by EliJArmstrong** [comment]
No problem. Thank you for assembling this package. I appreciate it.
