### ISSUE TITLE
a problem with this Menu script

### ISSUE THREAD

**Issue by TheApexDevil** [danqzq/unity-twitch-chat-interactions#2]
Assets\Scenes\Scripts\Menu.cs(18,13): error CS0103: The name 'TwitchManager' does not exist in the current context

**Comment by danqzq** [comment]
Is this issue present in the release (unity package)?

**Comment by TheApexDevil** [comment]
i didnt use the package file but the raw scripts
im going to try the package and give you a update

im new to unity so may just be me im a UE developer for 10 years so it works a little different
