### ISSUE TITLE
Acces user right in the command function?

### ISSUE THREAD

**Issue by szejmon** [danqzq/unity-twitch-chat-interactions#5]
Im kinda new to this is there a way to get the user that called a command right in the command function?

**Comment by danqzq** [comment]
Hey I just addressed this issue in the new v1.3 update!

You can now access which user is calling a command by setting the first parameter of type TwitchUser for your command function:
```csharp
[TwitchCommand("test")]
public void Test(TwitchUser user, string msg)
{
    Debug.Log($"{user.displayname} says {msg}");
}
```
